# Generated by Django 4.1.5 on 2023-05-22 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ('name',)},
        ),
        migrations.RenameField(
            model_name='chat',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='created_at',
        ),
        migrations.AddField(
            model_name='chat',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useravatar',
            name='img',
            field=models.ImageField(upload_to='userAvatar/'),
        ),
    ]
