# Generated by Django 4.1.5 on 2023-05-14 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_allarticletags_article_chat_community_communitychat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.SmallIntegerField()),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_recommendation_by_community', to='api.community')),
            ],
        ),
        migrations.CreateModel(
            name='RequestCommunityParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_in_community_by_community', to='api.community')),
            ],
        ),
        migrations.CreateModel(
            name='RequestUserSubscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UserBlacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='communitytags',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='biography_small',
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='useradditionalinformation',
            name='vk_profile',
        ),
        migrations.RemoveField(
            model_name='usersubscriptions',
            name='status',
        ),
        migrations.AddField(
            model_name='useradditionalinformation',
            name='website',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='communityparticipant',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_participant_by_community', to='api.community'),
        ),
        migrations.AlterField(
            model_name='communityparticipant',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.communityrole'),
        ),
        migrations.AlterField(
            model_name='communityparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_participant_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='communityrole',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='communitytag',
            name='tag',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='useradditionalinformation',
            name='other_info',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='useradditionalinformation',
            name='telegram_profile_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='useradditionalinformation',
            name='telegram_profile_link',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birthday',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='BannedUser',
        ),
        migrations.DeleteModel(
            name='CommunityTags',
        ),
        migrations.AddField(
            model_name='userblacklist',
            name='banned_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_blacklist_on_banned_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userblacklist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_blacklist_on_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requestusersubscriptions',
            name='subscriber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_user_subscriptions_on_subscriber', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requestusersubscriptions',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_user_subscriptions_on_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requestcommunityparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_in_community_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communityrecommendation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_recommendation_by_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
