# Generated by Django 4.1.5 on 2023-04-14 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communication_number', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Last_communication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('token', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_word', models.CharField(max_length=255)),
                ('word', models.CharField(max_length=255)),
                ('communication_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat_lm.communication')),
            ],
        ),
        migrations.AddField(
            model_name='communication',
            name='token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat_lm.token'),
        ),
    ]
